apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secrets.name }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  {{- (.Files.Glob (print "secrets/" .Values.env "/*")).AsSecrets | nindent 2 }}
