# GNU Lesser General Public License v3.0 only
# Copyright (C) 2020 Artefact
# licence-information@artefact.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
name: Doc

on:
  push:
    branches:
    - master


jobs:
  build_badge_and_update_doc:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest, upload coverage.
      run: |
        pip install pytest-cov webtest
        cov=`pytest --cov=./src/opt/app | grep TOTAL | awk '{print $4}'`
        curl -X POST -F repo_name=${{ github.repository }} -F badge_name=coverage -F value=$cov https://nautilus-badger.appspot.com/build_badge
      env:
        PYTHONPATH: /home/runner/work/nautilus-sftp-gateway/nautilus-sftp-gateway/src/opt/app
    - name: Get pylint note
      run: |
        pip install pylint
        pl=`pylint $(pwd)/**/*.py --disable=no-member | grep "Your code has been rated at " | awk '{print $7}'`
        curl -X POST -F repo_name=${{ github.repository }} -F badge_name=pylint -F value=$pl https://nautilus-badger.appspot.com/build_badge
      env:
        PYTHONPATH: /home/runner/work/nautilus-sftp-gateway/nautilus-sftp-gateway
    - name: Get cyclomatic complexity
      run: |
        pip install radon
        rad=`radon cc --average . | tail -1 | awk '{print $3}'`
        curl -X POST -F repo_name=${{ github.repository }} -F badge_name=complexity -F value=$rad https://nautilus-badger.appspot.com/build_badge
    - name: Get leaks from gitleaks
      run: |
        leaks=`docker run --rm --name gitleaks -v $(pwd):/code/ zricethezav/gitleaks --repo-path=/code/ -v --config=/code/gitleaks.toml | grep 'leaks detected' | awk '{print $2}'`
        if [[ $leaks -eq "No" ]]; then leaks="0"; fi
        curl -X POST -F repo_name=${{ github.repository }} -F badge_name=gitleaks -F value=$leaks https://nautilus-badger.appspot.com/build_badge
    - name: Checkout Wiki
      uses: actions/checkout@v2
      with:
        repository: artefactory/nautilus-sftp-gateway.wiki.git
        path: nautilus-sftp-gateway.wiki/
        persist-credentials: true
    - name: Update Wiki
      run : |
        sed -r "s/\.\/docs\/(.*)\.md/\.\/\1/g" README.md > ./docs/#-Home.md
        rm -f ./nautilus-sftp-gateway.wiki/*.md
        cp -r ./docs/ ./nautilus-sftp-gateway.wiki/
        cd nautilus-sftp-gateway.wiki/
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub-Actions"
        git add *
        git add -u
        git diff-index --quiet HEAD || git commit -m "[DOC] Updated wiki from GitHub actions"
        git push
        cd ..
        rm -rf nautilus-sftp-gateway.wiki/

